#!/usr/bin/env python3

import os
import platform
import subprocess
import sys

def is_windows():
    return platform.system() == "Windows"

def activate_command():
    """Returns the activation command based on the OS."""
    if is_windows():
        return os.path.join("venv", "Scripts", "activate.bat")
    else:
        return f"source venv/bin/activate"

def python_executable():
    """Get the path to the Python executable inside the virtual environment."""
    if is_windows():
        return os.path.join("venv", "Scripts", "python")
    else:
        return "venv/bin/python"
    
def create_venv():
    """Creates the virtual environment if it doesn't exist."""
    if not os.path.isdir("venv"):
        print("Creating virtual environment...")
        subprocess.check_call([sys.executable, "-m", "venv", "venv"])

def install_requirements():
    """Installs or updates the dependencies inside the virtual environment."""
    print("Installing/Updating dependencies...")
    subprocess.check_call([python_executable(), "-m", "pip", "install", "--upgrade", "pip"])
    subprocess.check_call([python_executable(), "-m", "pip", "install", "--upgrade", "-r", "requirements.txt"])

def parse_links():
    subprocess.check_call([python_executable(), "tools/parse_links"])

def download_data():
    subprocess.check_call([python_executable(), "tools/download_data"])

def delete_intermediate_files():
    os.remove("venv/intermediate.json")

def main():
    #create_venv()
    #install_requirements()
    parse_links()
    download_data()
    delete_intermediate_files()

if __name__ == "__main__":
    main()
